apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: user-profiles
  namespace: guestbook
  description: This API create and receives customer profiles
  annotations:
    "backstage.io/kubernetes-label-selector": "app.kubernetes.io/part-of=guestbook"
    'backstage.io/techdocs-ref': dir:.
  links:
    - url: https://api.agify.io
      title: API Definition
      icon: docs
spec:
  type: openapi
  lifecycle: experimental
  owner: java-spring-team
  system: guestbook/user-profile
  domain: guestbook/guestbook
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Artist API
      license:
        name: MIT
    servers:
      - url: http://artist.spotify.net/v1
    paths:
      /artists:
        get:
          summary: List all artists

