site_name: 'Guestbook API Docs'

nav:
  - Guestbook Application: index.md
  - Setup Developer Environment: developer_env.md
  - Deploy on local Workstation: deploy_local.md
  - Deploy on Kubernetes with TAP: deploy_tap.md

plugins:
  - techdocs-core
